//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisoDb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SisoDb.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item of type &apos;{0}&apos; has no Id member specified. A Guid or Int property named &apos;Id&apos; was expected..
        /// </summary>
        public static string AutoSchemaBuilder_MissingIdMember {
            get {
                return ResourceManager.GetString("AutoSchemaBuilder_MissingIdMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item of type &apos;{0}&apos; has no members that are indexable. There&apos;s no point in storing items that has nothing to index..
        /// </summary>
        public static string AutoSchemaBuilder_MissingIndexableMembers {
            get {
                return ResourceManager.GetString("AutoSchemaBuilder_MissingIndexableMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id property: &apos;{0}&apos;; is not of suported type. Only Guid and Int is accepted..
        /// </summary>
        public static string AutoSchemaBuilder_UnsupportedIdAccessorType {
            get {
                return ResourceManager.GetString("AutoSchemaBuilder_UnsupportedIdAccessorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connectionstring should have exactly two parts (&apos;{0}&apos; and &apos;{1}&apos;). Example: &apos;{2}&apos;..
        /// </summary>
        public static string ConnectionString_MissingParts {
            get {
                return ResourceManager.GetString("ConnectionString_MissingParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connectionstring is missing the Plain-part, indicated by &apos;{0}&apos;. Example: &apos;{1}&apos;..
        /// </summary>
        public static string ConnectionString_MissingPlainPart {
            get {
                return ResourceManager.GetString("ConnectionString_MissingPlainPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SisoDb-part is missing required key: &apos;provider&apos;..
        /// </summary>
        public static string ConnectionString_MissingProviderKey {
            get {
                return ResourceManager.GetString("ConnectionString_MissingProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connectionstring is missing the SisoDb-part, indicated by &apos;{0}&apos;. Example: &apos;{1}&apos;..
        /// </summary>
        public static string ConnectionString_MissingSisoDbPart {
            get {
                return ResourceManager.GetString("ConnectionString_MissingSisoDbPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct memberaccess of node: &apos;{0}&apos;; with with membertype: &apos;{1}&apos;; is not supported!.
        /// </summary>
        public static string ExpressionEvaluator_EvaluateMemberExpression_NotSupported {
            get {
                return ResourceManager.GetString("ExpressionEvaluator_EvaluateMemberExpression_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MemberExpression found in expression: &apos;{0}&apos;..
        /// </summary>
        public static string ExpressionUtils_GetRightMostMember_NoMemberFound {
            get {
                return ResourceManager.GetString("ExpressionUtils_GetRightMostMember_NoMemberFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sortings has allready been initialized..
        /// </summary>
        public static string GetCommand_SortingsAllreadyInitialized {
            get {
                return ResourceManager.GetString("GetCommand_SortingsAllreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id values must lie on the root object..
        /// </summary>
        public static string IdAccessor_GetIdValue_InvalidLevel {
            get {
                return ResourceManager.GetString("IdAccessor_GetIdValue_InvalidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property.PropertyType &apos;{0}&apos; is not supported by the IdAccessor..
        /// </summary>
        public static string IdAccessor_UnsupportedPropertyType {
            get {
                return ResourceManager.GetString("IdAccessor_UnsupportedPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Index-instance must be provided with a name..
        /// </summary>
        public static string Index_IsMissingName {
            get {
                return ResourceManager.GetString("Index_IsMissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no index storage schema value column matching the type &apos;{0}&apos;..
        /// </summary>
        public static string IndexStorageSchema_MissingValueSchemaField {
            get {
                return ResourceManager.GetString("IndexStorageSchema_MissingValueSchemaField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator type &apos;{0}&apos; can not be converted to &apos;IsNotNullOperatpr&apos; or &apos;NullOperator&apos;..
        /// </summary>
        public static string LambdaOperator_IsOrIsNot_NotSupported {
            get {
                return ResourceManager.GetString("LambdaOperator_IsOrIsNot_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; is not supported!.
        /// </summary>
        public static string LambdaOperator_OperatorTypeIsNotSupported {
            get {
                return ResourceManager.GetString("LambdaOperator_OperatorTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant only access a member in a query expression, you need to compare it against something. Eg. (x =&gt; x.HasItems) should be (x =&gt; x.HasItems == true).
        /// </summary>
        public static string LambdaParser_NoMemberExpressions {
            get {
                return ResourceManager.GetString("LambdaParser_NoMemberExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not evaluate the method call: &apos;{0}&apos;.
        ///Specific supported method exists as extensionmethods and are prefixed with &apos;Qx&apos;. Import namespace &apos;SisoDb.Querying&apos; to enable them..
        /// </summary>
        public static string LambdaParser_UnsupportedMethodCall {
            get {
                return ResourceManager.GetString("LambdaParser_UnsupportedMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion of values in expression is only allowed for nullable valuetypes..
        /// </summary>
        public static string LambdaParser_VisitUnary_InvalidConvert {
            get {
                return ResourceManager.GetString("LambdaParser_VisitUnary_InvalidConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unary operator &apos;{0}&apos; is not supported..
        /// </summary>
        public static string LambdaParser_VisitUnary_NotSupported {
            get {
                return ResourceManager.GetString("LambdaParser_VisitUnary_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node of type: &apos;{0}&apos; is not supported!.
        /// </summary>
        public static string ParsedSortingLambdaSqlProcessor_NotSupportedNodeType {
            get {
                return ResourceManager.GetString("ParsedSortingLambdaSqlProcessor_NotSupportedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant apply Unique on a member that is not of a simple type e.g. (int, string, bool) etc..
        /// </summary>
        public static string Property_Ctor_UniqueOnNonSimpleType {
            get {
                return ResourceManager.GetString("Property_Ctor_UniqueOnNonSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sortings has allready been initialized..
        /// </summary>
        public static string QueryCommandBuilder_SortingsAllreadyInitialized {
            get {
                return ResourceManager.GetString("QueryCommandBuilder_SortingsAllreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Where expression has allready been initialized..
        /// </summary>
        public static string QueryCommandBuilder_WhereAllreadyInitialized {
            get {
                return ResourceManager.GetString("QueryCommandBuilder_WhereAllreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided StorageProvider &apos;{0}&apos; is not supported..
        /// </summary>
        public static string SisoDbFactory_UnknownStorageProvider {
            get {
                return ResourceManager.GetString("SisoDbFactory_UnknownStorageProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only supported methods for marking sortings are Asc() and Desc()..
        /// </summary>
        public static string SortingParser_UnsupportedMethodForSortingDirection {
            get {
                return ResourceManager.GetString("SortingParser_UnsupportedMethodForSortingDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        public static string SqlDatabase_InitializeExisting_DbDoesNotExist {
            get {
                return ResourceManager.GetString("SqlDatabase_InitializeExisting_DbDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not flush a non transational DbClient..
        /// </summary>
        public static string SqlDbClient_Flus_NonTransactional {
            get {
                return ResourceManager.GetString("SqlDbClient_Flus_NonTransactional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A where clause can not be generated if the query command doesn&apos;t contain any where criterias..
        /// </summary>
        public static string SqlQueryGenerator_GenerateWhere {
            get {
                return ResourceManager.GetString("SqlQueryGenerator_GenerateWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Id could be extracted from the new structure..
        /// </summary>
        public static string SqlStructureSetUpdater_NewIdDoesNotExist {
            get {
                return ResourceManager.GetString("SqlStructureSetUpdater_NewIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id of the new structure &apos;{0}&apos; does not match the Id of the old structure &apos;{1}&apos;..
        /// </summary>
        public static string SqlStructureSetUpdater_NewIdDoesNotMatchOldId {
            get {
                return ResourceManager.GetString("SqlStructureSetUpdater_NewIdDoesNotMatchOldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Id could be extracted from the old structure..
        /// </summary>
        public static string SqlStructureSetUpdater_OldIdDoesNotExist {
            get {
                return ResourceManager.GetString("SqlStructureSetUpdater_OldIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value being retrieved is not of supported type. It must either be a string or the type needs to implement IConvertible or if Nullable&lt;T&gt;, then T needs to implement it..
        /// </summary>
        public static string StringConverter_AsString_TypeOfValueIsNotSupported {
            get {
                return ResourceManager.GetString("StringConverter_AsString_TypeOfValueIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Unique-index found for &apos;{0}&apos;.\r\nStructureId: &apos;{1}&apos;;Name: &apos;{2}&apos;;Value: &apos;{3}&apos;;.
        /// </summary>
        public static string Structure_DuplicateUniques {
            get {
                return ResourceManager.GetString("Structure_DuplicateUniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create StructureBuilderOptions for StructureIdType &apos;{0}&apos;..
        /// </summary>
        public static string StructureBuilderOptionsFactory_Create {
            get {
                return ResourceManager.GetString("StructureBuilderOptionsFactory_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using Guids the Id-property of the entity must be assigned before structure is created..
        /// </summary>
        public static string StructureIdFactory_MissingGuidValue {
            get {
                return ResourceManager.GetString("StructureIdFactory_MissingGuidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using Identities the Id-property of the entity must be assigned before structure is created..
        /// </summary>
        public static string StructureIdFactory_MissingIdentityValue {
            get {
                return ResourceManager.GetString("StructureIdFactory_MissingIdentityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity type: &apos;{0}&apos; is not supported..
        /// </summary>
        public static string StructureIdFactory_UnSupportedIdentityType {
            get {
                return ResourceManager.GetString("StructureIdFactory_UnSupportedIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only strings and valuetypes can be stored as indexes..
        /// </summary>
        public static string StructureIndex_ValueArgument_IncorrectType {
            get {
                return ResourceManager.GetString("StructureIndex_ValueArgument_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unique index &apos;{0}&apos;:&apos;{1}&apos; is evaluated to Null. This is not alowed..
        /// </summary>
        public static string StructureIndexesFactory_UniqueIndex_IsNull {
            get {
                return ResourceManager.GetString("StructureIndexesFactory_UniqueIndex_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported generic collections on model are: implementations of either IEnumerable&lt;T&gt; or IList&lt;T&gt;..
        /// </summary>
        public static string TypeExtensions_ExtractGenericType {
            get {
                return ResourceManager.GetString("TypeExtensions_ExtractGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UniqueModes &apos;{0}&apos; is unknow and cant be mapped..
        /// </summary>
        public static string UniqueModesCantBeMapped {
            get {
                return ResourceManager.GetString("UniqueModesCantBeMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of passed root items is not equal to the number of inserted root items!.
        /// </summary>
        public static string UnitOfWork_DoIdentityInsert_RootItemsMissmatch {
            get {
                return ResourceManager.GetString("UnitOfWork_DoIdentityInsert_RootItemsMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no &apos;{0}&apos;-structure to update matching the sent Id &apos;{1}&apos;..
        /// </summary>
        public static string UnitOfWork_NoItemExistsForUpdate {
            get {
                return ResourceManager.GetString("UnitOfWork_NoItemExistsForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator &apos;{0}&apos; is not supported for Qx-methods on enumerables..
        /// </summary>
        public static string WhereParser_QxEnumerables_OperatorNotSupported {
            get {
                return ResourceManager.GetString("WhereParser_QxEnumerables_OperatorNotSupported", resourceCulture);
            }
        }
    }
}
